export const itemObj = {
    aboutMyself: {
        position: '',
        surname: '',
        anotherSurname: '',
        name: '',
        middleName: '',
        dateBirthday: '',
        idNumber: '',
    },
    actualAdress: {
        region: '',
        district: '',
        city: '',
        street: '',
        house: '',
        apartment: '',
    },
    registrationAdress : {
        region: '',
        district: '',
        city: '',
        street: '',
        house: '',
        apartment: '',
    },
    contactsDataAndAnswers: {
        phone: '',
        email: '',
        contactsNetworks: '',
        findOut: null,
        dateStartWork: '',
        disabilityGroup: null,
        criminalOrAdministrativeResponse: null,
        relativesInCompany: null,
        aducation: '',
    },
    companyOne: {
        name: '',
        periodOfWork: '',
        duties: '',
        reasonForDismissal: '',
    },
    companyTwo: {
        name: '',
        periodOfWork: '',
        duties: '',
        reasonForDismissal: '',
    },
    consentPersonalData: true,
}