import { object, string, boolean} from 'yup';

export const validationQuestionarySchema = object({
    position: string().required(),
    surname: string().required(),
    anotherSurname: string().required(),
    name: string().required(),
    middleName: string().required(),
    dateBirthday: string().required(),
    idNumber: string().required(),
    actualRegion: string().required(),
    actualDistrict: string().required(),
    actualCity: string().required(),
    actualStreet: string().required(),
    actualHouse: string().required(),
    actualApartment: string().required(),
    registerRegion: string().required(),
    registerDistrict: string().required(),
    registerCity: string().required(),
    registerStreet: string().required(),
    registerHouse: string().required(),
    registerApartment: string().required(),
    phone: string().required(),
    email: string().email().required(),
    contactsNetworks: string().required(),
    findOut: string().required(),
    dateStartWork: string().required(),
    disabilityGroup: string().required(),
    criminalOrAdministrativeResponse: string().required(),
    relativesInCompany: string().required(),
    aducation: string().required(),
    companyOneName: string().required(),
    companyOnePeriodOfWork: string().required(),
    companyOneDuties: string().required(),
    companyOneReasonForDismissal: string().required(),
    companyTwoName: string().required(),
    companyTwoPeriodOfWork: string().required(),
    companyTwoDuties: string().required(),
    companyTwoReasonForDismissal: string().required(),
    consentPersonalData: boolean().required(),
}) 